### ISSUE TITLE
Frag Counter, Timer, Infinite Ammo, Wall Error

### ISSUE THREAD

**Issue by jagreetdg** [alghtryer/aimbotz#1]
Can't open Frag Count/Timer Using 'M' as shown in Video
No Infinite Ammo available. Ammo runs out as usual while firing
Lifting walls using upper buttons isn't working as well.

P.S. I have correctly installed the plugin
![20181025162139_1](https://user-images.githubusercontent.com/20647084/47495659-4a58b900-d872-11e8-89d3-de54efe94fa9.jpg)
![20181025161828_1](https://user-images.githubusercontent.com/20647084/47495661-4a58b900-d872-11e8-8f02-1e2a540ef463.jpg)
![20181025161942_1](https://user-images.githubusercontent.com/20647084/47495663-4af14f80-d872-11e8-9477-002ca9078bf2.jpg)

**Comment by alghtryer** [comment]
What you amxx version?
Do you have any error in addons/amxmodx/logs

Try start stopwatch with command on say /start /stop!

What other plugins do you have on the server?

You can't wall up/down when bot in game, you can remove bot(bot_quota 0), up or down wall and back bot in game(bot_quota 16).

**Comment by jagreetdg** [comment]
**Here is the Log Report from addons/amxmodx/logs**


``L 10/25/2018 - 16:03:09: -------- Mapchange to aimbotzbycha --------
L 10/25/2018 - 16:03:09: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 16:03:14: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 16:03:17: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 16:18:11: -------- Mapchange to aimbotzbycha --------
L 10/25/2018 - 16:18:11: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 16:18:13: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 16:18:14: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:02:24: -------- Mapchange to de_inferno --------
L 10/25/2018 - 22:02:24: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 22:02:33: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:02:36: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:03:42: -------- Mapchange to de_inferno --------
L 10/25/2018 - 22:03:42: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 22:03:44: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:03:45: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:23:02: -------- Mapchange to de_vertigo --------
L 10/25/2018 - 22:23:02: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 22:23:43: -------- Mapchange to de_vertigo --------
L 10/25/2018 - 22:23:43: [AMXX] Plugin "aim_botz.amxx" failed to load: Module/Library "cstrike" required for plugin.  Check modules.ini.
L 10/25/2018 - 22:23:45: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")
L 10/25/2018 - 22:23:46: [admin.amxx] Login: "v01dieJESUS<1><VALVE_ID_LOOPBACK><>" became an admin (account "loopback") (access "abcdefghijklmnopqrstu") (address "loopback")

**Comment by alghtryer** [comment]
You don't have cstrike module.

Maybe you forget download Counter-Strike Addon pack from amxmodx.
https://www.amxmodx.org/downloads.php

![screenshot-www amxmodx org-2018 10 26-18-10-26](https://user-images.githubusercontent.com/16125649/47578840-bc9ccc80-d94a-11e8-800c-e05a3e98e3b1.png)

**Comment by jagreetdg** [comment]
Thanks, That Solved the issue
